#!/bin/sh

## This script is designed to be called from a JAMF policy scoped to run once a day and ideally
## scoped to a Smart Group where software updates avaiable are greater than 0.
## If updates not requiring a restart a found it will call a policy in JAMF to install the softare updates. 
## This has the added benefit of resetting the machine's SUS to any defined in JAMF network segments. 
## If updates with restarts are found users are notified what the update is and that it the machine will be
## rebooted at the end of the update process. Users will then be given the option to reboot their machine or
## let it reboot automatically after 5 mins. Users can also defer the updates for x number of days before they 
## are automatically insatlled. It is recommended to also enable a self service policy in conjuction with this one 
## so users can install updates at a more appropriate time for them.

## Many thanks to the many people at www.jamfnation.com for providing the baisis and inspiration for this script 
## in partcular Mike Morales (@mm270) and his script found here
## https://github.com/mm2270/CasperSuiteScripts/blob/master/selectable_SoftwareUpdate.sh

## Define Global Variables
loggedInUser=""
AvailableUpdates=""
## Total amount of RestartReq="0update chances we will give the user
TotalAttempts="3"
## Final Chance is always 1 more then TotalAttempts can code this to just add 1 to 
## a blank FinalChance Variable which will require 1 less variable to update
FinalChance="4"
UpdateCount="0"
UpdateAttempts="0"
UpdateChancesLeft="0"
## Determine if a restart is required by updates. 0 for no and 1 for yes
RestartReq="0"
UpdateAttemptsFile="/etc/SUScount.txt"
JAMFHelperPath="/Library/Application Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper"
JAMFHelperIcon="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/FinderIcon.icns"
JAMFHelperTitle="Software Update"
JAMFHelperHeading="Software Updates Available"
JAMFHelperDescription="Please save all your work, quit open programs, and make sure your computer is plugged in.

This process will take approximately 5-10 minutes.

Once completed your computer will reboot and begin the upgrade."

## This if statement is designed to check for the location of the jamf binary in multiple 
## places due to changes in OSX associated with JAMF's upgrade to version 9.81
## References to the JAMF Binary must be changed to "$jamfBinary"
## Added 12/1/15 by tomr
##
if [ -e /usr/sbin/jamf ]
   then
       # JAMF Binary found at pre 9.81 location
       echo "JAMF Binary found at pre 9.81 location"
       jamfBinary="/usr/sbin/jamf"
       #
   elif [ -e /usr/local/jamf/bin/jamf ]
   then
      # JAMF Binary found at 9.81 or later location
      echo "JAMF Binary found at 9.81 or later location"
      jamfBinary="/usr/local/jamf/bin/jamf"
      #
   elif [ -e /usr/local/bin/jamf ]
   then
      # Alias to the JAMF Binary found
      echo "Alias to the JAMF Binary found"
      jamfBinary="/usr/local/bin/jamf"
      #
   else
   echo "JAMF Binary not found"
fi
## End JAMF Check if statement

## Set the Organization/Department/Division name. Used in dialog titles 

orgName=""

## If the file containing the number of software update attempts does not exist or has a size
## of RestartReq="0zero bytes then set the number of update attempts to zero by writing just a zero to the file

if [ ! -s "$UpdateAttemptsFile" ]
   then
   /bin/echo 0 > $UpdateAttemptsFile
fi

## Write the contents of UpdateAttemptsFile to a variable so it can be manipulated later
## and written back to the UpdateAttemptsFile based upon user input

UpdateCount=`/bin/cat $UpdateAttemptsFile`

##### Function to run if there are no updates that need to be restarted

installUpdatesNoRestart()
{
"$jamfBinary" policy -trigger runsoftwareupdate
/bin/echo 0 > $UpdateAttemptsFile
}

#### Function to run if there are updates that need to be restarted

updatesWithRestart()
{

loggedInUser=`ls -l /dev/console | /usr/bin/awk '{ print $3 }'`

if [ "$loggedInUser" != "root" ]
then
   UpdateChancesLeft=$((TotalAttempts - UpdateCount))
        if [ $UpdateChancesLeft = 0 ]
        then
           installMSG="Critical software updates are now running.
Please do not shut down your Mac or put it to sleep.
           
IMPORTANT:
We recommend saving any important documents now.
Your Mac will reboot in order to complete the update."
           
           "$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
           -icon "$JAMFHelperIcon" -iconSize 128 -heading "Software Updates Insralling" -alignHeading center -description "$installMSG" \
           -alignDescription center -timeout 15
           echo "Forced installation of software updates happening."
           installUpdates    
        else
           UpdateAttempts=$((UpdateCount + 1))
           InformativeTextMsg="The following is waiting to be installed and requires a restart of your computer:

$UpdatesReqRestart

This is user installation attempt $UpdateAttempts of $TotalAttempts.
           
Attempt $FinalChance will install updates automatically and your machine will restart."

           UserResponse=$("$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
               -icon "$JAMFHelperIcon" -iconSize 128 -heading "$JAMFHelperHeading" -alignHeading center -description "$InformativeTextMsg" \
               -alignDescription center -button1 "Install" -button2 "Cancel" -cancelButton 2 )
                if [ $UserResponse == 2 ]
                then
                   /bin/echo $UpdateAttempts > $UpdateAttemptsFile
                   echo "User choose to defer"
                   echo "This was user installation attempt $UpdateAttempts of $TotalAttempts."
                   exit 0
                elif [ $UserResponse == 0 ]
                then
                  echo "User choose to install Software Updates."
                  # We capture the JAMF Helper's PID so we can pass it to the disown command which removes it from
                  # the shell's list of watched jobs. The prevents debug messages from being generated when killing the process.
                  ## Disown works more reliably then using "wait" for the shell to release the job and piping the output to /dev/null
                  installUpdates
                fi
         fi
else
## No user logged in go ahead an install
"$jamfBinary" policy -trigger runsoftwareupdate
/bin/echo 0 > $UpdateAttemptsFile
fi

}

##	Function to install selected updates, updating progress bar with information
installUpdates ()
{

## When invoking this function there should be no JAMF helper windows running
## but jest in case there are check for the process, disown it, and kill it/

jamfHelperUID=$(pgrep jamfHelper)

if [ "$jamfHelperUID" != "" ]
then
   disown $jamfHelperUID
   killall jamfHelper
fi 


SoftwareUpdateMessage="   Installing Software Updates   
for macOS.

Your computer will reboot when finished."

"$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
-icon "$JAMFHelperIcon" -iconSize 96 -heading "Installing Updates" -alignHeading center -description "$SoftwareUpdateMessage" \
-alignDescription center &

jamfHelperUID=$(pgrep jamfHelper)
disown $jamfHelperUID

## Call the software update process
/usr/sbin/softwareupdate -i -a

## We put the recon here so it runs in the backgound and as the restart countdown begins.

"$jamfBinary" recon &

## Set the inital timer to 300 which will end up equating to 5 mins.
## We use let here so it is sure to asign the variable as a number.
## Probably not necessary but just in case.

let Counter="300"

## Check for the existence of the output file from the JAMF helper command
## left over from previous executions.

if [ -e /tmp/UserInput ]
   then
   rm /tmp/UserInput
fi

## Display a JAMF Helper window notifiying the user that a reboot in order to upgrade to Mojave will happen at 
## a specified period of time and give them the option to enable it immediately.
## We send the output to named pipe and keep the process running in the background which allows for two things.
## It keeps the window displayed but allows the while loop to start the countdown right away and by sending the 
## output of command to the nammed pipe we can then continually assign its contents to a variable inside the while
## loop allowing the if statement in that loop to check the status of the varible which equates to a user selecting
## to reboot immediately. If we didn't do it this way the output of the command would only get checked once when the 
## command initially ran.

RebootMsg="   Your computer will reboot in 5 mins.   

Please save all work and quit any open applications.

Click Reboot to start this process immediately."

FinalRebootMessage="   Your computer will reboot in 1 minute.   

Please save all work and quit all applications now."

killall jamfHelper

"$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
-icon "$JAMFHelperIcon" -iconSize 128 -heading "Software Updates Installed" -alignHeading center -description "$RebootMsg" \
-alignDescription center -button1 "Reboot" > /tmp/UserInput &

## While loop to run for at least 300 interations (which equals 5 mins) while checking certain conditions.
## We inject a 1 second sleep command into each run of the while loop to approximate 5 minutes. If we did not
## have the sleep command the loop would execute too quickly. Once the loop is over FileVault will be enabled
## and ther machine will reboot.

while [ "$Counter" != "0" ]
do
## Check contents of named pipe and assign it to UserResponse

UserResponse=$(cat /tmp/UserInput)

## If UserResponse equals 0 (return code of pushing the button) then we assume user has selected to reboot now so
## we run execute the enable Mojave Update policy and reboot the machine so it is enforced for the
## current user on login. We also set the counter 1 one as a safety mesaure in case it doesn't break out
## of the loop right away. One more subtraction from the counter variable would occure cuasing it to equal
## 0 which would also cause the loop to end and FileVault to enable. We could use a break statement here to
## but I liked this method.
## If the user response has not equated to 0 then we'll pop uo a window displaying that there is only 60
## seconds left before the Mojave update is started and a reboot happens. We must get the PID of the previous jamfHelper
## process and disown it first (to prevent unneccessary error messages) then kill it before we display the new
## message.

if [ "$UserResponse" == "0" ]
  then
     echo "User Choose to reboot immediately."
     Counter="1"
elif [ "$Counter" == 60 ]
  then
     jamfHelperUID=$(pgrep jamfHelper)
     disown $jamfHelperUID
     killall jamfHelper
     "$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
     -icon "$JAMFHelperIcon" -iconSize 128 -heading "Software Updates Installed" -alignHeading center -description "$FinalRebootMessage" \
     -alignDescription center &
fi
sleep 1
Counter=$((Counter - 1))
done

## Remove the named pipe

if [ -e /tmp/UserInput ]
   then
   rm /tmp/UserInput
fi

jamfHelperUID=$(pgrep jamfHelper)
disown $jamfHelperUID
killall jamfHelper

"$JAMFHelperPath" -windowType utility -title "$JAMFHelperTitle" \
-icon "$JAMFHelperIcon" -iconSize 128 -heading "Software Updates Installed" -alignHeading center -description "COMPUTER REBOOT TIME HAS ARRIVED" \
-alignDescription center &

## Delete the update countfile once just so it's gone
rm -r $UpdateAttemptsFile
echo "Rebooting the Machine" 
shutdown -r now

}

getUpdates()
{
rm /tmp/softwareupdates.txt

/usr/sbin/softwareupdate --list >> /tmp/softwareupdates.txt

UpdatesReqRestart=`cat /tmp/softwareupdates.txt | egrep 'restart|shutdown' | awk -F ',|\\\(' '{print$1}'`

UpdatesNoRestart=`cat /tmp/softwareupdates.txt | egrep -v 'restart|shutdown' | egrep recommended | awk -F ',|\\\(' '{print$1}'`

if [ "$UpdatesReqRestart" == "" ] && [ "$UpdatesNoRestart" == "" ]
   then
   echo "No new software to install"
      elif [ "$UpdatesReqRestart" != "" ]
      then
      RestartReq=1
      echo "Restarts required equals $RestartReq"
      updatesWithRestart
      elif [ "$UpdatesNoRestart" != "" ]
      then
      RestartReq=0
      echo "Restarts required equals $RestartReq"
      installUpdatesNoRestart
      fi
}

#### This activates the entire script

getUpdates
